sync-org: use ssh-agent and sleep 5m

diff --git a/bin/sync-org b/bin/sync-org
--- a/bin/sync-org
+++ b/bin/sync-org
@@ -1,15 +1,19 @@
-#!/bin/bash
+#!/usr/bin/env zsh
 
 cd ~/org
 
 while true; do
     git auto-commit -d -m 20
 
-    # Do a sync regardless of whether auto-commit did anything,
-    # because another remote may have pushed changes to our
-    # synced/master branch.
-    git \
-        -c remote.indian.annex-ignore=true \
-        annex sync
-    sleep 60
+    if detect_ssh_agent; then
+        # Do a sync regardless of whether auto-commit did anything,
+        # because another remote may have pushed changes to our
+        # synced/master branch.
+        git \
+            -c remote.indian.annex-ignore=true \
+            annex sync
+    else
+        echo >&2 "WARNING: can't connect to ssh-agent; skipping annex sync"
+    fi
+    sleep 5m
 done
